Feature/order crud
WeGoUpToMars/mars-payment-server pull request #20
Opened 2022-12-15 01:33 UTC by guswns3371

2022-12-15 01:53 UTC, yongyongkr requested changes
PR 다시 올려주시면 확인 후에 Approve 드리겠습니다!

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/application/OrderService.java
> +  public Response save(Request request) {
저는 OrderDto.Request로 쓰는데 static import에 대한 컨벤션을 맞추면 좋겠네요

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/presentation/dto/OrderDto.java
> +    private String orderUuid;
주문 생성 리퀘스트에 orderUuid가 생성될 수 있나요?
다른 기능때문에 추가된 필드라면 dto를 분리해야하지 않을까 싶어요.

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/application/OrderService.java
> +                                                     .map(product -> OrderProduct.create(order, product))
Jpa 연관관계 사용하면 OrderProduct를 만들 필요가 없을 것 같아요.

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +@AllArgsConstructor(access = AccessLevel.PROTECTED)
이거 Protected로 열어두는 이유가 있을가요?

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  private OrderStatus status = OrderStatus.ORDERED;
주문 생성 시에 Ordered로 초기화하는게 낫지 않을까요?

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
cascadeType을 ALL로 해두면 soft delete 안되지 않나요?

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  public static Order create(String orderUuid, Long amount, User user) {
validation이 더 필요할 것 같습니다. 예를 들어 금액은 0이상이라던지

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  private List<OrderProduct> orderProducts = new ArrayList<>();
OrderProduct를 가지는게 아니라 Product를 가져야 할 것 같네요.

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +                        .map(OrderProduct::getProduct)
이하 메서드들도 orderProducts가 아니라 products에 대해서 메서드 수정해야될 것 같습니다.

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +    Objects.requireNonNull(orderProducts);
update시 null 체크만 검증하면 되나요?

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  public void ordered() {
Order가 생성되면 status는 자동으로 Ordered가 될텐데 해당 메서드의 존재 이유가 무엇인가요?

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  public void processing() {
메서드 앞에 is를 붙이면 어떨까요?? 🤔

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/OrderProduct.java
> +  public static OrderProduct create(Order order, Product product) {
해당 객체는 jpa에 의해 자동 생성될 것 같은데 팩토리 메서드를 굳이 만들어야 할까요?

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/infra/OrderRepositoryImpl.java
> +    return orderJpa.findByUser(user);
user id로 찾도록 DataJpa가 쿼리를 내보내나요?? 신기하네요

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/order/presentation/dto/OrderDto.java
> +                     .id(order.getId())
id는 외부에 노출하지 않는게 좋을 것 같습니다.

2022-12-15 01:53 UTC, yongyongkr commented on src/main/java/com/mars/product/infra/ProductRepositoryImpl.java
> +    return jpa.findAllByIdIn(ids);
해당 쿼리 성능은 어떤가요?? 🤔

2022-12-15 01:54 UTC, guswns3371 commented on src/main/java/com/mars/order/application/OrderService.java
> +  public Response save(Request request) {
그러는게 좋을듯 합니다!!

2022-12-15 01:55 UTC, guswns3371 commented on src/main/java/com/mars/order/presentation/dto/OrderDto.java
> +    private String orderUuid;
주문이 들어간 이후에 order 고유아이디가 생성되겠네요..!
결제 시스템 플로우 이해가 부족했던것 같습니다 ㅠ

2022-12-18 06:37 UTC, guswns3371 commented on src/main/java/com/mars/order/application/OrderService.java
> +                                                     .map(product -> OrderProduct.create(order, product))
order와 product간의 매핑 관계를 OrderProduct로 정의해야하지 않나요?

2022-12-18 06:41 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  private List<OrderProduct> orderProducts = new ArrayList<>();
Product로 가지게 된다면 Order: Product = 1 : N 관계를 맺게 되지 않나요?
Product가 Order에 종속되는것 보다 Order와 Product간의 매핑 관계를 따로 가져가야할 거 같은데 어떻게 생각하시나요?

2022-12-18 06:43 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +    Objects.requireNonNull(orderProducts);
list 사이즈 체크도 같이 있으면 좋을것 같네요!!

2022-12-18 06:43 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  public void ordered() {
굳이 만들 필요없는 메소드였네요! 삭제하도록 하겠습니다~!

2022-12-18 06:44 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  public void processing() {
그게 더 의미 전달이 잘 될것 같네요!

2022-12-18 06:45 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/OrderProduct.java
> +  public static OrderProduct create(Order order, Product product) {
어떻게 jpa에 의해 자동 생성되나요?

2022-12-18 06:55 UTC, guswns3371 commented on src/main/java/com/mars/order/infra/OrderRepositoryImpl.java
> +    return orderJpa.findByUser(user);
아마 User 객체의 pk를 user_id로 세팅해서 쿼리를 생성하는것 같아요.

https://bcp0109.tistory.com/305
- findByUserId -> user와 left join 후 fk와 비교로 조회
- findByUser -> fk(user_id) 로 조회

2022-12-18 06:55 UTC, guswns3371 commented on src/main/java/com/mars/order/presentation/dto/OrderDto.java
> +                     .id(order.getId())
👍 은닉하겠습니당!

2022-12-18 07:11 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  public static Order create(String orderUuid, Long amount, User user) {
유효성 체크를 더 추가해두도록 하겠습니당!

2022-12-18 07:13 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
아 주문 상품 내역 soft delete 기능도 추가하는건가요?

추가하게 된다면
- CascadeType을 PERSIST로 변경하고
- 매핑 테이블에 active 여부를 체크할 수 있는 컬럼도 추가해야겠네요!

2022-12-18 07:15 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  private OrderStatus status = OrderStatus.ORDERED;
그럼 OrderStatus.WAIT로 초기화해두는게 바람직할거 같네요!

2022-12-18 07:18 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +@AllArgsConstructor(access = AccessLevel.PROTECTED)
AllArgsConstructor는 PRIVATE으로 하는게 좋을것 같네요!

2022-12-18 07:45 UTC, guswns3371 commented on src/main/java/com/mars/product/infra/ProductRepositoryImpl.java
> +    return jpa.findAllByIdIn(ids);
db 서버와 통신을 줄이고자 sql equal 조건 대신, in 절을 활용했습니다.

참고로, mysql in 절 쿼리가 내부적으로 equal + or 구문으로 변환이 된다고 합니다. 
(https://stackoverflow.com/questions/1013797/is-sql-in-bad-for-performance)
- `col IN ('a','b','c')` is rewritten to: `(COL = 'a') OR (COL = 'b') or (COL = 'c')`

2022-12-20 00:43 UTC, yongyongkr commented on src/main/java/com/mars/order/application/OrderService.java
> +                                                     .map(product -> OrderProduct.create(order, product))
OrderProduct는 jpa에서 자동 생성해주지 않을까요~?

2022-12-20 00:48 UTC, yongyongkr commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  private List<OrderProduct> orderProducts = new ArrayList<>();
https://cs-ssupport.tistory.com/m/482
그러네요 @ManyToMany에 조인 테이블 방식은 확장성이 없군요!

2022-12-20 00:54 UTC, yongyongkr commented on src/main/java/com/mars/order/infra/OrderRepositoryImpl.java
> +    return orderJpa.findByUser(user);
그렇네요!

2022-12-20 01:21 UTC, guswns3371 commented on src/main/java/com/mars/order/domain/entity/Order.java
> +  @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
soft delete는 추후에 기능 추가하죠!

2022-12-20 01:23 UTC, guswns3371 commented on src/main/java/com/mars/order/application/OrderService.java
> +                                                     .map(product -> OrderProduct.create(order, product))
자동 생성 안되는거 같아용

2022-12-20 01:24 UTC, guswns3371 commented on src/main/java/com/mars/order/presentation/dto/OrderDto.java
> +    private String orderUuid;
UUID.random 으로 자동 생성하도록 수정하겠슴둥

2022-12-20 01:27 UTC, merged